### ISSUE TITLE
gut diff: switch to diff bindings

### ISSUE THREAD

**Issue by naturallymitchell** [foundpatterns/gut#12]
https://github.com/foundpatterns/gut/blob/e4c77d2a7d7502a30ddb681217f0a4c62cdf2213/gut.lua#L150-L156

https://github.com/foundpatterns/torchbear/blob/master/src/bindings/text/diff.rs

**Comment by sineemore** [comment]
Completed in devel branch, will close on merge.

**Comment by sineemore** [comment]
Merged

**Comment by naturallymitchell** [comment]
https://github.com/foundpatterns/gut/compare/8a33005715b5...be4aaecb6e20
